### PR TITLE
Assignment5 @ZackWard-student

### PR DESCRIPTION
**Pull request by sammyboy2000**
Webapp:
https://icy-stone-0b3d2a71e.1.azurestaticapps.net/
API:
https://inconceivable-api.azurewebsites.net/swagger/index.html

### CODE REVIEW

**Comment by dcox2005** [comment]
from what I can tell, these sites are old, from assignment4.  The code looks to be the same as what was done in class.  Have you done any pushes from your local machine?

**Review by TylerRose8 — COMMENTED** [review]
Pagination, search, and the word list all look pretty good! It doesn't look like you have an account set up to test changing the commonality flag or adding words. The MasterOfTheUniverse claim and date of birth don't seem to be set up yet.

**Comment by ZackWard-student** [comment]
Seeded User Names 
"Admin@intellitect.com"                22yo Admin/Grant
"Administrator@intellitect.com"    Very Old Admin
"Orko@intellitect.com"                  2yo Admin/"Master Of The Universe"
"HeMan@intellitect.com"              39yo Admin/"Master Of The Universe"
"Guest@intellitect.com"                 0yo Grant

Password for all users: "P@ssw0rd123"

**Comment by hgill17** [comment]
Word search, pagination and words being sorted alphabetically all work without any issues. However I could not get any of the logins to work so I could not test the add and delete features. It appears that at login its throwing a 401 error.

**Pull request closed without merging**
