### PR TITLE
Assignment02 @hgill17

### PR DESCRIPTION
**Pull request by dcox2005**
https://zealous-coast-08a1d1310.1.azurestaticapps.net/

### CODE REVIEW

**Comment by tnadalini** [comment]
Everything looks good on this site. Only minor issue I noticed was the text for the hamburger menu looked a little wonky (aligned all the way to the left with no padding). Otherwise, everything looks good!

**Comment by TylerRose8** [comment]
The game features seem to work properly. The keyboard looks a little stretched out at first and doesn't quite scale correctly when the window becomes more narrow. I agree with the previous comment that your hamburger menu (great icon by the way) could use a little padding on the left. Your themes look good. I love the backward one too, I hope it makes it into the class repo!

**Comment by BenagainB** [comment]
I liked that you used the about page to list out the rules to the game and thought the Absurdle game was interesting to link to. When I opened the hamburger menu and then changed the color theme, then clicked the link to the game page, the app became unresponsive for a few minutes, so there might be some streamlining possible on options. Your Available words option is working very well, but input isn't scrubbed to make sure a real word is entered.

**Review by mmwoodfo — COMMENTED** [review]
This looks great guys!

**Review by mmwoodfo — COMMENTED** [review]
Your code is pretty clean, but there are some places that linter could have auto-fixed for you. Just be sure to run `npm run lintfix` before your final submission! (It looks like you ran it, then made some changes and didn't run it again)

**Pull request closed without merging**
