### PR TITLE
Assignment 1 @Matt Pennock

### PR DESCRIPTION
**Pull request by DakotaCondos**

### CODE REVIEW

**Comment by DakotaCondos** [comment]
Azure website link.
https://zealous-pond-0fc11401e.1.azurestaticapps.net

**Comment by PlantBrush** [comment]
Everything looks good for the assignment. It all matches the assignment specifications.

**Review by mmwoodfo — COMMENTED** [review]
In the future, just make sure that you are making a separate branch for your assignment, rather than making a PR using your main. Code changes showing up here in the PR should only be relevant to the assignment the PR is for.

Here is an example of a PR that uses an Assignment 1 branch: https://github.com/IntelliTect-Samples/EWU-CSCD379-2022-Spring/pull/11

Great job!

**Comment by mmwoodfo** [comment]
I don't see any extra credit done, but if I missed it just let me know where it is and I'll review the extra credit!

**Comment by mmwoodfo** [comment]
@MattPennock did you do a PR review?

**Pull request closed without merging**
