### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by dpeterson8**
Assignment 1 website link: https://gray-mushroom-0185eaa1e.1.azurestaticapps.net

### CODE REVIEW

**Comment by xiokd** [comment]
Everything looks good. The web app is working properly and appears to have met the specifications for the assignment.

**Comment by hgill17** [comment]
The website is working without any issues and does what the requirements asked for. The only thing I can suggest at this point is to make a minor change to the name of the game and have it something clever as mentioned in the requirements. Other than that I don't think you're missing anything.

**Comment by mmwoodfo** [comment]
In the future, just make sure that you are making a separate branch for your assignment, rather than making a PR using your main. Code changes showing up here in the PR should only be relevant to the assignment the PR is for.

Here is an example of a PR that uses an Assignment 1 branch: https://github.com/IntelliTect-Samples/EWU-CSCD379-2022-Spring/pull/11

Great job!

**Comment by mmwoodfo** [comment]
Did you partner for this assignment?

**Comment by dpeterson8** [comment]
> Did you partner for this assignment?



> Did you partner for this assignment?

I did not sorry I believe I had asked grant and he said it was alright not to on the first assignment, I may have misunderstood him as well.

**Comment by mmwoodfo** [comment]
@dpeterson8 I will follow up with Grant on Monday. :) Thanks for letting me know.

**Pull request closed without merging**
