### PR TITLE
Assignment5-Hewr&Tylor

### PR DESCRIPTION
**Pull request by hewrtarkhany**
web : https://wonderful-sky-0c6031910.1.azurestaticapps.net
Api : https://api-wordle.azurewebsites.net/swagger/index.html

### CODE REVIEW

**Comment by sammyboy2000** [comment]
While you're not quite finished yet, what code you do have looks promising. However, you seem to be having a CORS issue with your API calls. You should be able to fix it by:
1. Navigating to your API in portal.azure.com
2. Selecting CORS from the menu bar on the left.
3. Adding your webapp to the list of allowed origins.

**Comment by mpennock5** [comment]
The login page looks very clean, however when you click out of the field it disappears. So if someone doesn't type anything in it could be very confusing. It does not look like there is an endpoint for the wordlist yet but that page looks promising.

**Comment by mmwoodfo** [comment]
Looks like I'm getting a 403 when trying to view the word list as a non-logged in user:
image

**Comment by TylerRose8** [comment]
@mmwoodfo 
It looks like the controller was sitting in my unversioned files. This has been pushed and the workflows are currently running. So sorry!

**Pull request closed without merging**
