### PR TITLE
Assignment4

### PR DESCRIPTION
**Pull request by kelseymcmahon**
App:
https://red-desert-0f3146210.1.azurestaticapps.net/
API:
https://wordle-api-scoreboard.azurewebsites.net/swagger/index.html

### CODE REVIEW

**Comment by schuywalker** [comment]
ill review

**Comment by schuywalker** [comment]
website theme absolutely fire :)

iPhoneSE tiles and keyboard is jumbled. might want to center and shrink the elements on the iPad Air setting so the player doesnt have to scroll to the side. Youre getting a lot of extra room on the right hand side. everything else looks good on all sizes though! 

looks like youre having some back end issues as are most of us. Im sure youre very aware of a lot of these things already... 
- candidate display not getting words, and ? gets entered into the game.
- When you win the game, theres option to play another game. maybe also prompt them to enter their name?
- I got PHASE as the word twice in a row? suspicious.
- havent been able to get on the leader board once I should be.

**Comment by hgill17** [comment]
The website is really well made. There are just some minor things that need to be fixed. For the iPhone SE and the Galaxy Note display the player name box goes behind the tiles. And while playing the game I did notice that the ? key option didn't give me the correct word in the hints list when I had some of the letters for the word. Also the requirements say to Add an instructions page that is available via the hamburger menu that details the features of the game and how to play, you did include the instructions they just need to be part of the hamburger menu.

**Review by mmwoodfo — COMMENTED** [review]
I pushed some changes to this PR - those changes are pretty much the code reivew.

**Pull request closed without merging**
