### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by AntonioGomez12**
link: https://calm-mud-0e2c94b10.1.azurestaticapps.net

extra credit:

1. Add difficulty by increasing word sizes
2. Make it harder to solve by erasing correct guesses after a few more attempts
3. Add a bookworm image that congratulates when puzzle is solved

### CODE REVIEW

**Comment by PlantBrush** [comment]
Nice job on the assignment, I like your use of the card on the game page. One thing that it is missing according to the assignment specifications is that there should be a button to take you back to the home page from the game page.

**Review by tnadalini — COMMENTED** [review]
Create a Nuxt app ✅
        Uses TypeScript ✅
        Update Vue components to TypeScript ✅
        Uses Vuetify ✅
        Uses Jest ❌

    Create a simple page called game.vue ✅
        Page should have a card with a heading that with a clever name for the game ✅
        some default placeholder body text ✅
        and a button to take you back to the home page✅
        there should be a button the home page to access this page ✅

    Check all the code into your repo fork ✅

    Create a static web app in Azure ✅
        Create the container where your GitHub repo will deploy
        Link the site with your GitHub repo

    Update the CI/CD pipeline ✅
        Pipeline runs on each check in
        Jest tests run and pass ✅
        Nuxt app builds ✅
        Nuxt app deploys to Azure ✅

    Azure site works ✅
        Post your Azure URL in your readme.md file. Replace the URL in the readme with your URL. ✅

Extra Credit

    Come up with up to three unique ideas for stories we could implement as part of our project. Post these in your readme.md. ❌
    One point per idea up to three points

Good job, I would just suggest adding your extra credit suggestions to your ReadMe file

**Comment by mmwoodfo** [comment]
In the future, just make sure that you are making a separate branch for your assignment, rather than making a PR using your main. Code changes showing up here in the PR should only be relevant to the assignment the PR is for.

Here is an example of a PR that uses an Assignment 1 branch: https://github.com/IntelliTect-Samples/EWU-CSCD379-2022-Spring/pull/11

Great job!

**Comment by mmwoodfo** [comment]
Did you have a partner for this assignment?

**Comment by mmwoodfo** [comment]
> link: https://calm-mud-0e2c94b10.1.azurestaticapps.net
> 
> extra credit:
> 
> 1. Add difficulty by increasing word sizes
> 2. Make it harder to solve by erasing correct guesses after a few more attempts
> 3. Add a bookworm image that congratulates when puzzle is solved

Great EC suggestions, if you have time, these should be added under the issues tab here: https://github.com/IntelliTect-Samples/EWU-CSCD379-2022-Spring/issues

**Pull request closed without merging**
